package com.epam.jdi.bookstore.restassured.base;

public interface Token {
    String TOKEN = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ7XCJpZFwiOjEsXCJuYW1lXCI6XCJhZG1pbkBlcGFtLmNvbVwiLFwicGFzc3dvcmRcIjpcIiQyYSQxMCRCRWViSlYyV0NVUG5ka0x2WWlEYkIuMU1tdnNkSXZjZFFJaEQ2MG1qL0lYbXk5UWFVY0JXeVwiLFwicm9sZXNcIjpbXX0iLCJpYXQiOjE1OTE3NzI3MjEsImV4cCI6MTY0MDk4NDQwMH0.FFLc6cwSPQhpyVAWkUc3hfRm4-IiCCKL6LRsOCo3A0BbZaCPoRdOHtaHB1ADC6m_L_9bUZBLrp9NKOcq1jrQOw";
}
