/*
 * Bookstore API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.dtoGenerated;


import java.util.Objects;

/**
 * Address
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-30T18:44:18.739+03:00[Europe/Moscow]")
public class Address {

    private Long id = null;

    private Long userId = null;

    private String fullName = null;

    private String addressLine1 = null;

    private String addressLine2 = null;

    private String postal = null;

    private String city = null;

    private String region = null;

    private String country = null;

    /**
     * Get id
     *
     * @return id
     **/
    public Long getId() {
        return id;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    public Long getUserId() {
        return userId;
    }

    public Address fullName(String fullName) {
        this.fullName = fullName;
        return this;
    }


    /**
     * Get fullName
     *
     * @return fullName
     **/
    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Address addressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
        return this;
    }


    /**
     * Get addressLine1
     *
     * @return addressLine1
     **/
    public String getAddressLine1() {
        return addressLine1;
    }

    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    public Address addressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
        return this;
    }


    /**
     * Get addressLine2
     *
     * @return addressLine2
     **/
    public String getAddressLine2() {
        return addressLine2;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    public Address postal(String postal) {
        this.postal = postal;
        return this;
    }


    /**
     * Get postal
     *
     * @return postal
     **/
    public String getPostal() {
        return postal;
    }

    public void setPostal(String postal) {
        this.postal = postal;
    }

    public Address city(String city) {
        this.city = city;
        return this;
    }


    /**
     * Get city
     *
     * @return city
     **/
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Address region(String region) {
        this.region = region;
        return this;
    }


    /**
     * Get region
     *
     * @return region
     **/
    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public Address country(String country) {
        this.country = country;
        return this;
    }


    /**
     * Get country
     *
     * @return country
     **/
    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Address address = (Address) o;
        return Objects.equals(this.id, address.id) &&
                Objects.equals(this.userId, address.userId) &&
                Objects.equals(this.fullName, address.fullName) &&
                Objects.equals(this.addressLine1, address.addressLine1) &&
                Objects.equals(this.addressLine2, address.addressLine2) &&
                Objects.equals(this.postal, address.postal) &&
                Objects.equals(this.city, address.city) &&
                Objects.equals(this.region, address.region) &&
                Objects.equals(this.country, address.country);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(id, userId, fullName, addressLine1, addressLine2, postal, city, region, country);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Address {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
        sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
        sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
        sb.append("    postal: ").append(toIndentedString(postal)).append("\n");
        sb.append("    city: ").append(toIndentedString(city)).append("\n");
        sb.append("    region: ").append(toIndentedString(region)).append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
