/*
 * Bookstore API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.dtoGenerated;


import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Book
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-30T18:44:18.739+03:00[Europe/Moscow]")
public class Book {

    private Long id = null;

    private String isbn = null;

    private String title = null;

    private String author = null;

    private String publicationYear = null;

    private String price = null;

    private Integer quantity = null;

    private List<Genre> genres = null;

    /**
     * Get id
     *
     * @return id
     **/
    public Long getId() {
        return id;
    }

    public Book isbn(String isbn) {
        this.isbn = isbn;
        return this;
    }


    /**
     * Get isbn
     *
     * @return isbn
     **/
    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public Book title(String title) {
        this.title = title;
        return this;
    }


    /**
     * Get title
     *
     * @return title
     **/
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Book author(String author) {
        this.author = author;
        return this;
    }


    /**
     * Get author
     *
     * @return author
     **/
    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Book publicationYear(String publicationYear) {
        this.publicationYear = publicationYear;
        return this;
    }


    /**
     * Get publicationYear
     *
     * @return publicationYear
     **/
    public String getPublicationYear() {
        return publicationYear;
    }

    public void setPublicationYear(String publicationYear) {
        this.publicationYear = publicationYear;
    }

    public Book price(String price) {
        this.price = price;
        return this;
    }


    /**
     * Get price
     *
     * @return price
     **/
    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Book quantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }


    /**
     * Get quantity
     *
     * @return quantity
     **/
    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Book genres(List<Genre> genres) {
        this.genres = genres;
        return this;
    }

    public Book addGenresItem(Genre genresItem) {
        if (this.genres == null) {
            this.genres = new ArrayList<>();
        }
        this.genres.add(genresItem);
        return this;
    }

    /**
     * Get genres
     *
     * @return genres
     **/
    public List<Genre> getGenres() {
        return genres;
    }

    public void setGenres(List<Genre> genres) {
        this.genres = genres;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Book book = (Book) o;
        return Objects.equals(this.id, book.id) &&
                Objects.equals(this.isbn, book.isbn) &&
                Objects.equals(this.title, book.title) &&
                Objects.equals(this.author, book.author) &&
                Objects.equals(this.publicationYear, book.publicationYear) &&
                Objects.equals(this.price, book.price) &&
                Objects.equals(this.quantity, book.quantity) &&
                Objects.equals(this.genres, book.genres);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(id, isbn, title, author, publicationYear, price, quantity, genres);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Book {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    isbn: ").append(toIndentedString(isbn)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    author: ").append(toIndentedString(author)).append("\n");
        sb.append("    publicationYear: ").append(toIndentedString(publicationYear)).append("\n");
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
        sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
        sb.append("    genres: ").append(toIndentedString(genres)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
